### ISSUE TITLE
rhc port-forward not work

### ISSUE THREAD

**Issue by 452** [openshift/rhc#690] opened 2015-06-04 12:17 UTC
I have started WildFly 8 server( http://www.zinrad.com/ ):
rs-emetemunoy.rhcloud.com
server already started and still work... but I can't port forward on my local machine
```sh
ihor@ihor-M50Vc:$ rhc port-forward rs
Checking available ports ... none
There are no available ports to forward for this application. Your application may be stopped or idled.
ihor@ihor-M50Vc:$ rhc port-forward -a rs
Checking available ports ... none
There are no available ports to forward for this application. Your application may be stopped or idled.
```
in tail I have:

>
2015-06-04 07:33:47,439 INFO  [javax.enterprise.resource.webcontainer.jsf.config] (MSC service thread 1-8) Initializing Mojarra 2.2.8-jbossorg-1 20140822-1131 for context ''
2015-06-04 07:33:48,991 WARN  [org.hornetq.core.server] (hornetq-failure-check-thread) HQ222082: error on connection failure check: java.lang.OutOfMemoryError: unable to create new native thread
	at java.lang.Thread.start0(Native Method) [rt.jar:1.8.0_45]
	at java.lang.Thread.start(Thread.java:714) [rt.jar:1.8.0_45]
	at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:950) [rt.jar:1.8.0_45]
	at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1357) [rt.jar:1.8.0_45]
	at org.hornetq.utils.OrderedExecutorFactory$OrderedExecutor.execute(OrderedExecutorFactory.java:133) [hornetq-core-client-2.4.5.Final.jar:]
	at org.hornetq.core.remoting.server.impl.RemotingServiceImpl$FailureCheckAndFlushThread.run(RemotingServiceImpl.java:739) [hornetq-server-2.4.5.Final.jar:]
2015-06-04 07:33:49,758 ERROR [stderr] (hornetq-expiry-reaper-thread) Exception in thread "hornetq-expiry-reaper-thread" java.lang.OutOfMemoryError: unable to create new native thread
2015-06-04 07:33:49,759 ERROR [stderr] (hornetq-expiry-reaper-thread) 	at java.lang.Thread.start0(Native Method)
2015-06-04 07:33:49,759 ERROR [stderr] (hornetq-expiry-reaper-thread) 	at java.lang.Thread.start(Thread.java:714)
2015-06-04 07:33:49,760 ERROR [stderr] (hornetq-expiry-reaper-thread) 	at java.util.concurrent.ThreadPoolExecutor.addWorker(ThreadPoolExecutor.java:950)
2015-06-04 07:33:49,760 ERROR [stderr] (hornetq-expiry-reaper-thread) 	at java.util.concurrent.ThreadPoolExecutor.execute(ThreadPoolExecutor.java:1357)
2015-06-04 07:33:49,760 ERROR [stderr] (hornetq-expiry-reaper-thread) 	at org.hornetq.utils.OrderedExecutorFactory$OrderedExecutor.execute(OrderedExecutorFactory.java:133)
2015-06-04 07:33:49,761 ERROR [stderr] (hornetq-expiry-reaper-thread) 	at org.hornetq.core.server.impl.QueueImpl.expireReferences(QueueImpl.java:1540)
2015-06-04 07:33:49,761 ERROR [stderr] (hornetq-expiry-reaper-thread) 	at org.hornetq.core.postoffice.impl.PostOfficeImpl$Reaper.run(PostOfficeImpl.java:1414)
2015-06-04 07:33:49,761 ERROR [stderr] (hornetq-expiry-reaper-thread) 	at java.lang.Thread.run(Thread.java:745)
2015-06-04 07:34:02,363 INFO  [org.wildfly.extension.undertow] (MSC service thread 1-8) JBAS017534: Registered web context: /
2015-06-04 07:34:02,645 INFO  [org.jboss.as.server] (ServerService Thread Pool -- 32) JBAS018559: Deployed "ROOT.war" (runtime-name : "ROOT.war")
2015-06-04 07:34:02,843 INFO  [org.jboss.as] (Controller Boot Thread) JBAS015961: Http management interface listening on http://127.3.241.1:9990/management
2015-06-04 07:34:02,843 INFO  [org.jboss.as] (Controller Boot Thread) JBAS015951: Admin console listening on http://127.3.241.1:9990
2015-06-04 07:34:02,844 INFO  [org.jboss.as] (Controller Boot Thread) JBAS015874: WildFly 8.2.0.Final "Tweek" started in 90366ms - Started 648 of 777 services (178 services are lazy, passive or on-demand)

version of rhc:
>
Successfully installed rhc-1.35.3
Installing ri documentation for rhc-1.35.3
Installing darkfish documentation for rhc-1.35.3
Gems updated: rhc

**Comment by 452** [comment] 2015-06-06 13:10
after delete and recreate application, port-forward work;

but one time I have this error:

```sh
$ rhc port-forward rs -d
DEBUG: Using config file /home/ihor/.openshift/express.conf
DEBUG: Git config 'git config --get rhc.app-id' returned ''
DEBUG: Git config 'git config --get rhc.app-name' returned ''
DEBUG: Git config 'git config --get rhc.domain-name' returned ''
DEBUG: Authenticating with RHC::Auth::Token
DEBUG: Connecting to https://openshift.redhat.com/broker/rest/api
DEBUG: Getting all domains
DEBUG: Client supports API versions 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7
DEBUG: Created new httpclient
DEBUG: Request GET https://openshift.redhat.com/broker/rest/api
DEBUG:    code 200  948 ms
DEBUG: Server supports API versions 1.0, 1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7
DEBUG:    Using API version 1.7
DEBUG: Client API version 1.7 is not current. Refetching API
DEBUG: Request GET https://openshift.redhat.com/broker/rest/api
DEBUG:    code 200  218 ms
DEBUG: Using token authentication
DEBUG: Request GET https://openshift.redhat.com/broker/rest/domains
DEBUG:    code 200  265 ms
DEBUG: Using token authentication
DEBUG: Request GET https://openshift.redhat.com/broker/rest/domain/emetemunoy/application/rs
DEBUG:    code 200  294 ms
Checking available ports ... /var/lib/gems/1.9.1/gems/net-ssh-2.9.1/lib/net/ssh/transport/packet_stream.rb:87:in `next_packet': connection closed by remote host (Net::SSH::Disconnect)
	from /var/lib/gems/1.9.1/gems/net-ssh-2.9.1/lib/net/ssh/transport/session.rb:178:in `block in poll_message'
	from /var/lib/gems/1.9.1/gems/net-ssh-2.9.1/lib/net/ssh/transport/session.rb:173:in `loop'
	from /var/lib/gems/1.9.1/gems/net-ssh-2.9.1/lib/net/ssh/transport/session.rb:173:in `poll_message'
	from /var/lib/gems/1.9.1/gems/net-ssh-2.9.1/lib/net/ssh/connection/session.rb:460:in `dispatch_incoming_packets'
	from /var/lib/gems/1.9.1/gems/net-ssh-2.9.1/lib/net/ssh/connection/session.rb:221:in `preprocess'
	from /var/lib/gems/1.9.1/gems/net-ssh-2.9.1/lib/net/ssh/connection/session.rb:205:in `process'
	from /var/lib/gems/1.9.1/gems/net-ssh-2.9.1/lib/net/ssh/connection/session.rb:169:in `block in loop'
	from /var/lib/gems/1.9.1/gems/net-ssh-2.9.1/lib/net/ssh/connection/session.rb:169:in `loop'
	from /var/lib/gems/1.9.1/gems/net-ssh-2.9.1/lib/net/ssh/connection/session.rb:169:in `loop'
	from /var/lib/gems/1.9.1/gems/net-ssh-2.9.1/lib/net/ssh/connection/session.rb:118:in `close'
	from /var/lib/gems/1.9.1/gems/net-ssh-2.9.1/lib/net/ssh.rb:212:in `ensure in start'
	from /var/lib/gems/1.9.1/gems/net-ssh-2.9.1/lib/net/ssh.rb:212:in `start'
	from /var/lib/gems/1.9.1/gems/rhc-1.35.3/lib/rhc/commands/port_forward.rb:85:in `run'
	from /var/lib/gems/1.9.1/gems/rhc-1.35.3/lib/rhc/commands.rb:294:in `execute'
	from /var/lib/gems/1.9.1/gems/rhc-1.35.3/lib/rhc/commands.rb:285:in `block (3 levels) in to_commander'
	from /var/lib/gems/1.9.1/gems/commander-4.2.1/lib/commander/command.rb:180:in `call'
	from /var/lib/gems/1.9.1/gems/commander-4.2.1/lib/commander/command.rb:180:in `call'
	from /var/lib/gems/1.9.1/gems/commander-4.2.1/lib/commander/command.rb:155:in `run'
	from /var/lib/gems/1.9.1/gems/commander-4.2.1/lib/commander/runner.rb:421:in `run_active_command'
	from /var/lib/gems/1.9.1/gems/rhc-1.35.3/lib/rhc/command_runner.rb:72:in `run!'
	from /var/lib/gems/1.9.1/gems/commander-4.2.1/lib/commander/delegates.rb:12:in `run!'
	from /var/lib/gems/1.9.1/gems/rhc-1.35.3/lib/rhc/cli.rb:37:in `start'
	from /var/lib/gems/1.9.1/gems/rhc-1.35.3/bin/rhc:20:in `<top (required)>'
	from /usr/local/bin/rhc:23:in `load'
	from /usr/local/bin/rhc:23:in `<main>'
```

**Comment by tiwillia** [comment] 2015-07-10 13:34
@452, it looks like you are experiencing Out-Of-Memory errors on your gear. This means that your application is using more memory or threads than it is allowed to use. When this happens, processes on the gear will start to be killed and the whole application could be killed.

In the first post you made, we can see the following in the logs. This leads me to believe that you are hitting the thread limit for small gears (250 iirc) and are unable to create any new threads:
```
2015-06-04 07:33:48,991 WARN org.hornetq.core.server HQ222082: error on connection failure check: java.lang.OutOfMemoryError: unable to create new native thread
```

The second issue you are having after re-creating your application was likely caused by the port-forward action putting the memory usage (or more likely, the thread usage) of your application over the limit. The ssh process forwarding your ports was likely killed due to exceeding these limits.

The best way to resolve this issue is to re-create your application with a bigger gear size, giving the application more memory to work with. You can also limit the number of threads that are used by Wildfly. See this [Stackoverflow](http://stackoverflow.com/questions/27579015/getting-out-of-memory-error-when-restarting-wildfly-on-openshift) thread on exactly this problem.

@danmcp we can close this. It is not an issue with rhc, but a usage issue with wildfly + openshift

**Closed** 2015-07-10 13:59 UTC
